# Generated by Django 5.2.8 on 2025-11-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Car manufacturer (e.g., Toyota, Ford)', max_length=100)),
                ('model', models.CharField(help_text='Car model name', max_length=100)),
                ('year', models.IntegerField(help_text='Manufacturing year')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('certified', 'Certified Pre-Owned')], default='used', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('mileage', models.IntegerField(blank=True, help_text='Mileage in miles', null=True)),
                ('description', models.TextField(blank=True)),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=17, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
